name: Automating The Build and Deployment to Production of Home Service Platform API

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main 



jobs:
  build-backend:
    environment:
      name: backend-prod 
    runs-on: ubuntu-latest


  test-backend:
    runs-on: ubuntu-latest
    needs: [build-backend] 


  deploy-backend:
    runs-on: ubuntu-latest
    needs: [test-backend]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "YOUR APP's NAME" #Must be unique in Heroku
          heroku_email: "YOUR EMAIL"
          appdir: "microservice-1/admin" 



  build-frontend:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2


  test-frontend:
    runs-on: ubuntu-latest
    needs: [build-frontend]
    steps: 
      - uses: actions/checkout@v2


  deploy-frontend:
    runs-on: ubuntu-latest
    needs: [test-frontend]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "YOUR APP's NAME" #Must be unique in Heroku
          heroku_email: "YOUR EMAIL"
          appdir: "vue-crud" 
